export const CHANGE_USER = "CHANGE_USER";

// For Order
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const ADD_ORDER_TOTAL_AMOUNT = 'ADD_ORDER_TOTAL_AMOUNT';
export const ADD_SHOP_DETAILS = 'ADD_SHOP_DETAILS';
export const ADD_PRODUCT_FOR_ORDER = 'ADD_PRODUCT_FOR_ORDER';
export const RESET_PRODUCTS_FOR_ORDER = 'RESET_PRODUCTS_FOR_ORDER';
export const ADD_GEOLOCATION_FOR_ORDER = 'ADD_GEOLOCATION_FOR_ORDER';
export const ADD_SHOP_PICTURE_FOR_ORDER = 'ADD_SHOP_PICTURE_FOR_ORDER';
export const ADD_ORDER_DISCOUNT = 'ADD_ORDER_DISCOUNT';
export const ADD_ATTACHMENT_TO_ORDER = 'ADD_ATTACHMENT_TO_ORDER';
export const RESET_SHOP_PICTURE_FOR_ORDER = 'RESET_SHOP_PICTURE_FOR_ORDER';

export const ADD_DELIVERY_DATE_FOR_ORDER = 'ADD_DELIVERY_DATE_FOR_ORDER';
export const ADD_ISSUE_DATE_FOR_ORDER = 'ADD_ISSUE_DATE_FOR_ORDER';


export const PUSH_ORDER_TO_RECEIVED_LIST = 'PUSH_ORDER_TO_RECEIVED_LIST';

// For Products
export const ADD_ITEM = "ADD_ITEM";
export const REDUCE_ITEM = "REDUCE_ITEM";


// for Shops
export const ADD_SHOP_NAME = "ADD_SHOP_NAME";
export const ADD_SHOP_OWNER_NAME = 'ADD_SHOP_OWNER_NAME';
export const ADD_SHOP_OWNER_ID = 'ADD_SHOP_OWNER_ID';
export const ADD_SHOP_OWNER_CELL = 'ADD_SHOP_OWNER_CELL';
export const ADD_SHOP_TO_REGISTERED_LIST = 'ADD_SHOP_TO_REGISTERED_LIST';
export const ADD_ORDER_TO_SHOP = 'ADD_ORDER_TO_SHOP';