// For Order
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const ADD_PRODUCT_FOR_ORDER = 'ADD_PRODUCT_FOR_ORDER';
export const RESET_PRODUCTS_FOR_ORDER = 'RESET_PRODUCTS_FOR_ORDER';
export const ADD_QUANTITY_FOR_ORDER = 'ADD_QUANTITY_FOR_ORDER';
export const ADD_GEOLOCATION_FOR_ORDER = 'ADD_GEOLOCATION_FOR_ORDER';
export const ADD_SHOP_PICTURE_FOR_ORDER = 'ADD_SHOP_PICTURE_FOR_ORDER';
export const RESET_SHOP_PICTURE_FOR_ORDER = 'RESET_SHOP_PICTURE_FOR_ORDER';

export const ADD_DELIVERY_DATE_FOR_ORDER = 'ADD_DELIVERY_DATE_FOR_ORDER';
export const ADD_ISSUE_DATE_FOR_ORDER = 'ADD_ISSUE_DATE_FOR_ORDER';


export const PUSH_ORDER_TO_RECEIVED_LIST = 'PUSH_ORDER_TO_RECEIVED_LIST';

// For Products
export const ADD_ITEM = "ADD_ITEM";
export const REDUCE_ITEM = "REDUCE_ITEM";
